'use strict';

// Deterministic 64x64 RGBA8 test image for the P0-3 LUT reference benchmark.
// It is generated by code so that no binary image file has to live in the repository,
// and every consumer (reference generator, error benchmark, tests) rebuilds the exact
// same bytes. Do not change this file without bumping `id` and regenerating
// `reference-outputs.json`.

const id = 'p0-synthetic-rgba-image-v1';
const width = 64;
const height = 64;
const sliceBlue = Object.freeze([0, 128, 255]);
const lcgSeed = 0x2545f491;

const rows = Object.freeze([
  'rows 0-15: RGB cube slice, B = 0, R = ramp(x), G = (y % 16) * 17, A = 255',
  'rows 16-31: RGB cube slice, B = 128, R = ramp(x), G = (y % 16) * 17, A = 255',
  'rows 32-47: RGB cube slice, B = 255, R = ramp(x), G = (y % 16) * 17, A = 255',
  'row 48: neutral ramp, R = G = B = ramp(x), A = 255',
  'row 49: neutral ramp with alpha ramp, R = G = B = A = ramp(x)',
  'row 50: red ramp (ramp(x), 0, 0, 255)',
  'row 51: green ramp (0, ramp(x), 0, 255)',
  'row 52: blue ramp (0, 0, ramp(x), 255)',
  'row 53: cyan ramp (0, ramp(x), ramp(x), 255)',
  'row 54: magenta ramp (ramp(x), 0, ramp(x), 255)',
  'row 55: yellow ramp (ramp(x), ramp(x), 0, 255)',
  'rows 56-59: LCG noise RGB, A = 255',
  'rows 60-63: LCG noise RGB and LCG noise A',
  'ramp(x) = Math.round(x * 255 / 63) for x in 0..63',
  'LCG: seed 0x2545f491, state = (state * 1664525 + 1013904223) mod 2^32, byte = state >>> 24',
]);

const probes = Object.freeze([
  { index: 0, name: 'slice0-black' },
  { index: 63, name: 'slice0-red' },
  { index: 960, name: 'slice0-green' },
  { index: 1023, name: 'slice0-yellow' },
  { index: 1568, name: 'slice1-interior' },
  { index: 2048, name: 'slice2-blue' },
  { index: 2111, name: 'slice2-magenta' },
  { index: 3071, name: 'slice2-white' },
  { index: 3104, name: 'gray-ramp-mid' },
  { index: 3136, name: 'alpha-ramp-zero' },
  { index: 3168, name: 'alpha-ramp-mid' },
  { index: 3584, name: 'noise-opaque-first' },
  { index: 4095, name: 'noise-alpha-last' },
]);

function ramp(x) {
  return Math.round((x * 255) / 63);
}

function build() {
  const data = new Uint8ClampedArray(width * height * 4);
  let state = lcgSeed;
  const nextByte = () => {
    state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
    return state >>> 24;
  };

  for (let y = 0; y < height; y += 1) {
    for (let x = 0; x < width; x += 1) {
      const value = ramp(x);
      let rgba;
      if (y < 48) rgba = [value, (y % 16) * 17, sliceBlue[Math.floor(y / 16)], 255];
      else if (y === 48) rgba = [value, value, value, 255];
      else if (y === 49) rgba = [value, value, value, value];
      else if (y === 50) rgba = [value, 0, 0, 255];
      else if (y === 51) rgba = [0, value, 0, 255];
      else if (y === 52) rgba = [0, 0, value, 255];
      else if (y === 53) rgba = [0, value, value, 255];
      else if (y === 54) rgba = [value, 0, value, 255];
      else if (y === 55) rgba = [value, value, 0, 255];
      else if (y < 60) rgba = [nextByte(), nextByte(), nextByte(), 255];
      else rgba = [nextByte(), nextByte(), nextByte(), nextByte()];
      data.set(rgba, (y * width + x) * 4);
    }
  }
  return data;
}

module.exports = Object.freeze({ id, width, height, rows, probes, build });
